# Generated by Django 5.1.1 on 2024-09-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
