# Generated by Django 5.1.1 on 2024-09-23 14:33

import register_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=register_login.models.user_avatar_path),
        ),
    ]
