# Generated by Django 5.1.1 on 2024-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamers',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
